# vim: ft=yaml:sw=2

name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: True
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: uv sync --dev
      - run: uv run pytest -vv

  ruff-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: True
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: uv sync --dev
      - run: uv run ruff check --no-fix --diff

  ruff-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: True
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: uv sync --dev
      - run: uv run ruff format --diff --check
